### ISSUE TITLE
issue after sign in on SeaT 1.0.1

### ISSUE THREAD

**Issue by warlof** [eveseat/services#1]
After a test setup and init the admin account, I try to sign in using its credentials.
I got an error after clicking on submit button issue on this line https://github.com/eveseat/services/blob/master/src/Settings/Settings.php#L78

After a quick check, it appears that static::$model is empty.

**Comment by ValidError** [comment]
From what I can tell, it looks like it is trying to pull the settings for the 'admin' account. However they don't exist in the database.

**Comment by leonjza** [comment]
> From what I can tell, it looks like it is trying to pull the settings for the 'admin' account. However they don't exist in the database.

Correct. It wll get the defaults [here](https://github.com/eveseat/services/blob/master/src/Settings/Profile.php#L65) if there are no settings for the user.

**Comment by leonjza** [comment]
Closing the issue tracking on this repository. Please use the eveseat/seat repo for issue tracking.
