### ISSUE TITLE
issue on views calling img helper

### ISSUE THREAD

**Issue by warlof** [eveseat/services#2]
Foreach views calling img function from helpers, there is an issue from https://github.com/eveseat/services/blob/master/src/Image/Eve.php#L90

$id parameter can be a string (like https://github.com/eveseat/web/blob/master/src/resources/views/api/list.blade.php#L55)

Suggestion : using intval function instead of is_int which return 0 if the value can't be parsed : http://php.net/manual/fr/function.intval.php

**Comment by leonjza** [comment]
Could you give an example of a error that it generates? May just use `is_numeric()`.
